/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
#define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
#define _NAMESPACE_CONCAT(NS, ID) NS ## ID
#define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
#define CASADI_PREFIX(ID) FORCESNLPsolver_model_1_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "FORCESNLPsolver.h"

#define PRINTF printf
FORCESNLPsolver_float CASADI_PREFIX(sq)(FORCESNLPsolver_float x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

FORCESNLPsolver_float CASADI_PREFIX(sign)(FORCESNLPsolver_float x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const solver_int32_default CASADI_PREFIX(s0)[] = {11, 1, 0, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10};
#define s0 CASADI_PREFIX(s0)
static const solver_int32_default CASADI_PREFIX(s1)[] = {12, 1, 0, 12, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11};
#define s1 CASADI_PREFIX(s1)
static const solver_int32_default CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const solver_int32_default CASADI_PREFIX(s3)[] = {1, 11, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const solver_int32_default CASADI_PREFIX(s4)[] = {2, 1, 0, 2, 0, 1};
#define s4 CASADI_PREFIX(s4)
static const solver_int32_default CASADI_PREFIX(s5)[] = {2, 11, 0, 0, 0, 0, 2, 4, 5, 5, 5, 5, 6, 7, 0, 1, 0, 1, 1, 1, 1};
#define s5 CASADI_PREFIX(s5)
static const solver_int32_default CASADI_PREFIX(s6)[] = {8, 1, 0, 8, 0, 1, 2, 3, 4, 5, 6, 7};
#define s6 CASADI_PREFIX(s6)
static const solver_int32_default CASADI_PREFIX(s7)[] = {8, 11, 0, 2, 4, 6, 7, 8, 9, 11, 13, 15, 16, 17, 0, 3, 1, 4, 2, 5, 0, 1, 2, 0, 3, 1, 4, 2, 5, 6, 7};
#define s7 CASADI_PREFIX(s7)
/* evaluate_stages */
solver_int32_default FORCESNLPsolver_model_1(const FORCESNLPsolver_float **arg, FORCESNLPsolver_float **res) 
{
    FORCESNLPsolver_float a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25,a26,a27,a28,a29,a30,a31,a32,a33,a34,a35,a36,a37;
    a0=arg[0] ? arg[0][0] : 0;
    a1=sq(a0);
    a2=arg[0] ? arg[0][1] : 0;
    a3=sq(a2);
    a1=(a1+a3);
    a3=arg[0] ? arg[0][2] : 0;
    a4=sq(a3);
    a1=(a1+a4);
    a4=arg[0] ? arg[0][5] : 0;
    a5=3.;
    a5=(a4-a5);
    a6=sq(a5);
    a7=10000.;
    a6=(a7*a6);
    a1=(a1+a6);
    a6=arg[0] ? arg[0][3] : 0;
    a8=arg[0] ? arg[0][9] : 0;
    a9=(a6-a8);
    a10=sq(a9);
    a11=1.0000000000000000e-03;
    a10=(a11+a10);
    a12=arg[0] ? arg[0][4] : 0;
    a13=arg[0] ? arg[0][10] : 0;
    a14=(a12-a13);
    a15=sq(a14);
    a10=(a10+a15);
    a15=(a6-a8);
    a16=sq(a15);
    a17=(a12-a13);
    a18=sq(a17);
    a16=(a16+a18);
    a18=sq(a4);
    a16=(a16+a18);
    a18=sq(a16);
    a19=(a18*a10);
    a19=(a11+a19);
    a20=(a6-a8);
    a21=(a20*a4);
    a22=arg[0] ? arg[0][6] : 0;
    a23=arg[1] ? arg[1][10] : 0;
    a24=(a22-a23);
    a25=(a21*a24);
    a26=(a12-a13);
    a27=(a26*a4);
    a28=arg[0] ? arg[0][7] : 0;
    a29=arg[1] ? arg[1][11] : 0;
    a30=(a28-a29);
    a31=(a27*a30);
    a25=(a25+a31);
    a31=(a6-a8);
    a32=sq(a31);
    a33=(a12-a13);
    a34=sq(a33);
    a32=(a32+a34);
    a34=arg[0] ? arg[0][8] : 0;
    a35=(a34*a32);
    a25=(a25-a35);
    a35=sq(a25);
    a35=(a35/a19);
    a36=(a7*a35);
    a1=(a1+a36);
    if (res[0]!=0) res[0][0]=a1;
    a1=(a0+a0);
    if (res[1]!=0) res[1][0]=a1;
    a1=(a2+a2);
    if (res[1]!=0) res[1][1]=a1;
    a1=(a3+a3);
    if (res[1]!=0) res[1][2]=a1;
    a25=(a25+a25);
    a1=(a7/a19);
    a25=(a25*a1);
    a24=(a24*a25);
    a1=(a4*a24);
    a31=(a31+a31);
    a36=(a34*a25);
    a31=(a31*a36);
    a37=(a1-a31);
    a15=(a15+a15);
    a16=(a16+a16);
    a35=(a35/a19);
    a35=(a7*a35);
    a10=(a10*a35);
    a16=(a16*a10);
    a15=(a15*a16);
    a37=(a37-a15);
    a9=(a9+a9);
    a18=(a18*a35);
    a9=(a9*a18);
    a37=(a37-a9);
    if (res[1]!=0) res[1][3]=a37;
    a30=(a30*a25);
    a37=(a4*a30);
    a33=(a33+a33);
    a33=(a33*a36);
    a36=(a37-a33);
    a17=(a17+a17);
    a17=(a17*a16);
    a36=(a36-a17);
    a14=(a14+a14);
    a14=(a14*a18);
    a36=(a36-a14);
    if (res[1]!=0) res[1][4]=a36;
    a26=(a26*a30);
    a20=(a20*a24);
    a26=(a26+a20);
    a20=(a4+a4);
    a20=(a20*a16);
    a26=(a26-a20);
    a5=(a5+a5);
    a7=(a7*a5);
    a26=(a26+a7);
    if (res[1]!=0) res[1][5]=a26;
    a21=(a21*a25);
    if (res[1]!=0) res[1][6]=a21;
    a27=(a27*a25);
    if (res[1]!=0) res[1][7]=a27;
    a32=(a32*a25);
    a32=(-a32);
    if (res[1]!=0) res[1][8]=a32;
    a31=(a31-a1);
    a31=(a31+a15);
    a31=(a31+a9);
    if (res[1]!=0) res[1][9]=a31;
    a33=(a33-a37);
    a33=(a33+a17);
    a33=(a33+a14);
    if (res[1]!=0) res[1][10]=a33;
    a33=arg[1] ? arg[1][6] : 0;
    a33=(a6-a33);
    a14=sq(a33);
    a17=arg[1] ? arg[1][7] : 0;
    a17=(a12-a17);
    a37=sq(a17);
    a14=(a14+a37);
    if (res[2]!=0) res[2][0]=a14;
    a14=(a6-a8);
    a37=sq(a14);
    a31=(a12-a13);
    a9=sq(a31);
    a37=(a37+a9);
    a37=(a37+a11);
    a11=sqrt(a37);
    a9=atan2(a11,a4);
    if (res[2]!=0) res[2][1]=a9;
    a33=(a33+a33);
    if (res[3]!=0) res[3][0]=a33;
    a14=(a14+a14);
    a33=sq(a4);
    a37=(a37+a33);
    a33=(a4/a37);
    a9=(a11+a11);
    a33=(a33/a9);
    a14=(a14*a33);
    if (res[3]!=0) res[3][1]=a14;
    a17=(a17+a17);
    if (res[3]!=0) res[3][2]=a17;
    a31=(a31+a31);
    a31=(a31*a33);
    if (res[3]!=0) res[3][3]=a31;
    a11=(a11/a37);
    a11=(-a11);
    if (res[3]!=0) res[3][4]=a11;
    a14=(-a14);
    if (res[3]!=0) res[3][5]=a14;
    a31=(-a31);
    if (res[3]!=0) res[3][6]=a31;
    a31=5.0000000000000003e-02;
    a14=(a31*a0);
    a14=(a22+a14);
    a11=2.;
    a14=(a11*a14);
    a14=(a22+a14);
    a37=(a31*a0);
    a37=(a22+a37);
    a37=(a11*a37);
    a14=(a14+a37);
    a37=1.0000000000000001e-01;
    a33=(a37*a0);
    a33=(a22+a33);
    a14=(a14+a33);
    a33=1.6666666666666666e-02;
    a14=(a33*a14);
    a6=(a6+a14);
    if (res[4]!=0) res[4][0]=a6;
    a6=(a31*a2);
    a6=(a28+a6);
    a6=(a11*a6);
    a6=(a28+a6);
    a14=(a31*a2);
    a14=(a28+a14);
    a14=(a11*a14);
    a6=(a6+a14);
    a14=(a37*a2);
    a14=(a28+a14);
    a6=(a6+a14);
    a6=(a33*a6);
    a12=(a12+a6);
    if (res[4]!=0) res[4][1]=a12;
    a12=(a31*a3);
    a12=(a34+a12);
    a12=(a11*a12);
    a12=(a34+a12);
    a31=(a31*a3);
    a31=(a34+a31);
    a31=(a11*a31);
    a12=(a12+a31);
    a31=(a37*a3);
    a31=(a34+a31);
    a12=(a12+a31);
    a12=(a33*a12);
    a4=(a4+a12);
    if (res[4]!=0) res[4][2]=a4;
    a4=(a11*a0);
    a4=(a0+a4);
    a12=(a11*a0);
    a4=(a4+a12);
    a4=(a4+a0);
    a4=(a33*a4);
    a22=(a22+a4);
    if (res[4]!=0) res[4][3]=a22;
    a22=(a11*a2);
    a22=(a2+a22);
    a4=(a11*a2);
    a22=(a22+a4);
    a22=(a22+a2);
    a22=(a33*a22);
    a28=(a28+a22);
    if (res[4]!=0) res[4][4]=a28;
    a28=(a11*a3);
    a28=(a3+a28);
    a22=(a11*a3);
    a28=(a28+a22);
    a28=(a28+a3);
    a28=(a33*a28);
    a34=(a34+a28);
    if (res[4]!=0) res[4][5]=a34;
    a34=(a11*a23);
    a34=(a23+a34);
    a28=(a11*a23);
    a34=(a34+a28);
    a34=(a34+a23);
    a34=(a33*a34);
    a8=(a8+a34);
    if (res[4]!=0) res[4][6]=a8;
    a8=(a11*a29);
    a8=(a29+a8);
    a11=(a11*a29);
    a8=(a8+a11);
    a8=(a8+a29);
    a33=(a33*a8);
    a13=(a13+a33);
    if (res[4]!=0) res[4][7]=a13;
    a13=5.0000000000000010e-03;
    if (res[5]!=0) res[5][0]=a13;
    if (res[5]!=0) res[5][1]=a37;
    if (res[5]!=0) res[5][2]=a13;
    if (res[5]!=0) res[5][3]=a37;
    if (res[5]!=0) res[5][4]=a13;
    if (res[5]!=0) res[5][5]=a37;
    a13=1.;
    if (res[5]!=0) res[5][6]=a13;
    if (res[5]!=0) res[5][7]=a13;
    if (res[5]!=0) res[5][8]=a13;
    if (res[5]!=0) res[5][9]=a37;
    if (res[5]!=0) res[5][10]=a13;
    if (res[5]!=0) res[5][11]=a37;
    if (res[5]!=0) res[5][12]=a13;
    if (res[5]!=0) res[5][13]=a37;
    if (res[5]!=0) res[5][14]=a13;
    if (res[5]!=0) res[5][15]=a13;
    if (res[5]!=0) res[5][16]=a13;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_init(solver_int32_default *f_type, solver_int32_default *n_in, solver_int32_default *n_out, solver_int32_default *sz_arg, solver_int32_default *sz_res) 
{
    *f_type = 1;
    *n_in = 2;
    *n_out = 6;
    *sz_arg = 2;
    *sz_res = 6;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_sparsity(solver_int32_default i, solver_int32_default *nrow, solver_int32_default *ncol, const solver_int32_default **colind, const solver_int32_default **row) 
{
    const solver_int32_default *s;
    switch (i) 
    {
      case 0:
        s = s0;
        break;
      case 1:
        s = s1;
        break;
      case 2:
        s = s2;
        break;
      case 3:
        s = s3;
        break;
      case 4:
        s = s4;
        break;
      case 5:
        s = s5;
        break;
      case 6:
        s = s6;
        break;
      case 7:
        s = s7;
        break;
      default:
        return 1;
    }
    
    *nrow = s[0];
    *ncol = s[1];
    *colind = s + 2;
    *row = s + 2 + (*ncol + 1);
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_work(solver_int32_default *sz_iw, solver_int32_default *sz_w) 
{
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 38;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
