/* This function was automatically generated by CasADi */
#ifdef __cplusplus
extern "C" {
#endif

#ifdef CODEGEN_PREFIX
#define NAMESPACE_CONCAT(NS, ID) _NAMESPACE_CONCAT(NS, ID)
#define _NAMESPACE_CONCAT(NS, ID) NS ## ID
#define CASADI_PREFIX(ID) NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else /* CODEGEN_PREFIX */
#define CASADI_PREFIX(ID) FORCESNLPsolver_model_1_ ## ID
#endif /* CODEGEN_PREFIX */

#include <math.h>

#include "FORCESNLPsolver/include/FORCESNLPsolver.h"

#define PRINTF printf
FORCESNLPsolver_float CASADI_PREFIX(sq)(FORCESNLPsolver_float x) { return x*x;}
#define sq(x) CASADI_PREFIX(sq)(x)

FORCESNLPsolver_float CASADI_PREFIX(sign)(FORCESNLPsolver_float x) { return x<0 ? -1 : x>0 ? 1 : x;}
#define sign(x) CASADI_PREFIX(sign)(x)

static const solver_int32_default CASADI_PREFIX(s0)[] = {9, 1, 0, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8};
#define s0 CASADI_PREFIX(s0)
static const solver_int32_default CASADI_PREFIX(s1)[] = {0, 1, 0, 0};
#define s1 CASADI_PREFIX(s1)
static const solver_int32_default CASADI_PREFIX(s2)[] = {1, 1, 0, 1, 0};
#define s2 CASADI_PREFIX(s2)
static const solver_int32_default CASADI_PREFIX(s3)[] = {1, 9, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 0, 0, 0, 0, 0, 0, 0, 0};
#define s3 CASADI_PREFIX(s3)
static const solver_int32_default CASADI_PREFIX(s4)[] = {1, 9, 0, 0, 0, 0, 1, 2, 2, 2, 2, 2, 0, 0};
#define s4 CASADI_PREFIX(s4)
static const solver_int32_default CASADI_PREFIX(s5)[] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
#define s5 CASADI_PREFIX(s5)
static const solver_int32_default CASADI_PREFIX(s6)[] = {6, 9, 0, 2, 4, 6, 7, 8, 9, 11, 13, 15, 0, 3, 1, 4, 2, 5, 0, 1, 2, 0, 3, 1, 4, 2, 5};
#define s6 CASADI_PREFIX(s6)
/* evaluate_stages */
solver_int32_default FORCESNLPsolver_model_1(const FORCESNLPsolver_float **arg, FORCESNLPsolver_float **res) 
{
    FORCESNLPsolver_float a0,a1,a2,a3,a4,a5,a6,a7,a8,a9,a10,a11,a12,a13,a14,a15,a16,a17,a18,a19,a20,a21,a22,a23,a24,a25;
    
    a0=arg[0] ? arg[0][0] : 0;
    a1=sq(a0);
    a2=10000.;
    a1=(a2*a1);
    a3=arg[0] ? arg[0][1] : 0;
    a4=sq(a3);
    a4=(a2*a4);
    a1=(a1+a4);
    a4=arg[0] ? arg[0][2] : 0;
    a5=sq(a4);
    a5=(a2*a5);
    a1=(a1+a5);
    a5=arg[0] ? arg[0][5] : 0;
    a6=2.;
    a7=(a5-a6);
    a8=sq(a7);
    a9=10.;
    a8=(a9*a8);
    a1=(a1+a8);
    a8=arg[0] ? arg[0][3] : 0;
    a10=sq(a8);
    a11=arg[0] ? arg[0][4] : 0;
    a12=sq(a11);
    a10=(a10+a12);
    a12=sq(a8);
    a13=sq(a11);
    a12=(a12+a13);
    a13=sq(a5);
    a12=(a12+a13);
    a13=sq(a12);
    a14=(a13*a10);
    a15=(a8*a5);
    a16=arg[0] ? arg[0][6] : 0;
    a17=(a15*a16);
    a18=(a11*a5);
    a19=arg[0] ? arg[0][7] : 0;
    a20=(a18*a19);
    a17=(a17+a20);
    a20=sq(a8);
    a21=sq(a11);
    a20=(a20+a21);
    a21=arg[0] ? arg[0][8] : 0;
    a22=(a21*a20);
    a17=(a17-a22);
    a22=sq(a17);
    a22=(a22/a14);
    a23=100000.;
    a24=(a23*a22);
    a1=(a1+a24);
    if (res[0]!=0) res[0][0]=a1;
    a1=(a0+a0);
    a1=(a2*a1);
    if (res[1]!=0) res[1][0]=a1;
    a1=(a3+a3);
    a1=(a2*a1);
    if (res[1]!=0) res[1][1]=a1;
    a1=(a4+a4);
    a2=(a2*a1);
    if (res[1]!=0) res[1][2]=a2;
    a17=(a17+a17);
    a2=(a23/a14);
    a17=(a17*a2);
    a2=(a16*a17);
    a1=(a5*a2);
    a24=(a8+a8);
    a25=(a21*a17);
    a24=(a24*a25);
    a1=(a1-a24);
    a24=(a8+a8);
    a12=(a12+a12);
    a22=(a22/a14);
    a23=(a23*a22);
    a10=(a10*a23);
    a12=(a12*a10);
    a24=(a24*a12);
    a1=(a1-a24);
    a24=(a8+a8);
    a13=(a13*a23);
    a24=(a24*a13);
    a1=(a1-a24);
    if (res[1]!=0) res[1][3]=a1;
    a1=(a19*a17);
    a24=(a5*a1);
    a23=(a11+a11);
    a23=(a23*a25);
    a24=(a24-a23);
    a23=(a11+a11);
    a23=(a23*a12);
    a24=(a24-a23);
    a23=(a11+a11);
    a23=(a23*a13);
    a24=(a24-a23);
    if (res[1]!=0) res[1][4]=a24;
    a1=(a11*a1);
    a2=(a8*a2);
    a1=(a1+a2);
    a2=(a5+a5);
    a2=(a2*a12);
    a1=(a1-a2);
    a7=(a7+a7);
    a9=(a9*a7);
    a1=(a1+a9);
    if (res[1]!=0) res[1][5]=a1;
    a15=(a15*a17);
    if (res[1]!=0) res[1][6]=a15;
    a18=(a18*a17);
    if (res[1]!=0) res[1][7]=a18;
    a20=(a20*a17);
    a20=(-a20);
    if (res[1]!=0) res[1][8]=a20;
    a20=sq(a8);
    a17=sq(a11);
    a20=(a20+a17);
    if (res[2]!=0) res[2][0]=a20;
    a20=(a8+a8);
    if (res[3]!=0) res[3][0]=a20;
    a20=(a11+a11);
    if (res[3]!=0) res[3][1]=a20;
    a20=(a16+a0);
    a20=(a6*a20);
    a20=(a16+a20);
    a17=(a16+a0);
    a17=(a6*a17);
    a20=(a20+a17);
    a17=(a6*a0);
    a17=(a16+a17);
    a20=(a20+a17);
    a17=3.3333333333333331e-001;
    a20=(a17*a20);
    a8=(a8+a20);
    if (res[4]!=0) res[4][0]=a8;
    a8=(a19+a3);
    a8=(a6*a8);
    a8=(a19+a8);
    a20=(a19+a3);
    a20=(a6*a20);
    a8=(a8+a20);
    a20=(a6*a3);
    a20=(a19+a20);
    a8=(a8+a20);
    a8=(a17*a8);
    a11=(a11+a8);
    if (res[4]!=0) res[4][1]=a11;
    a11=(a21+a4);
    a11=(a6*a11);
    a11=(a21+a11);
    a8=(a21+a4);
    a8=(a6*a8);
    a11=(a11+a8);
    a8=(a6*a4);
    a8=(a21+a8);
    a11=(a11+a8);
    a11=(a17*a11);
    a5=(a5+a11);
    if (res[4]!=0) res[4][2]=a5;
    a5=(a6*a0);
    a5=(a0+a5);
    a11=(a6*a0);
    a5=(a5+a11);
    a5=(a5+a0);
    a5=(a17*a5);
    a16=(a16+a5);
    if (res[4]!=0) res[4][3]=a16;
    a16=(a6*a3);
    a16=(a3+a16);
    a5=(a6*a3);
    a16=(a16+a5);
    a16=(a16+a3);
    a16=(a17*a16);
    a19=(a19+a16);
    if (res[4]!=0) res[4][4]=a19;
    a19=(a6*a4);
    a19=(a4+a19);
    a16=(a6*a4);
    a19=(a19+a16);
    a19=(a19+a4);
    a17=(a17*a19);
    a21=(a21+a17);
    if (res[4]!=0) res[4][5]=a21;
    if (res[5]!=0) res[5][0]=a6;
    if (res[5]!=0) res[5][1]=a6;
    if (res[5]!=0) res[5][2]=a6;
    if (res[5]!=0) res[5][3]=a6;
    if (res[5]!=0) res[5][4]=a6;
    if (res[5]!=0) res[5][5]=a6;
    a21=1.;
    if (res[5]!=0) res[5][6]=a21;
    if (res[5]!=0) res[5][7]=a21;
    if (res[5]!=0) res[5][8]=a21;
    if (res[5]!=0) res[5][9]=a6;
    if (res[5]!=0) res[5][10]=a21;
    if (res[5]!=0) res[5][11]=a6;
    if (res[5]!=0) res[5][12]=a21;
    if (res[5]!=0) res[5][13]=a6;
    if (res[5]!=0) res[5][14]=a21;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_init(solver_int32_default *f_type, solver_int32_default *n_in, solver_int32_default *n_out, solver_int32_default *sz_arg, solver_int32_default *sz_res) 
{
    *f_type = 1;
    *n_in = 2;
    *n_out = 6;
    *sz_arg = 2;
    *sz_res = 6;
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_sparsity(solver_int32_default i, solver_int32_default *nrow, solver_int32_default *ncol, const solver_int32_default **colind, const solver_int32_default **row) 
{
    const solver_int32_default *s;
    switch (i) 
    {
      case 0:
        s = s0;
        break;
      case 1:
        s = s1;
        break;
      case 2:
      case 4:
        s = s2;
        break;
      case 3:
        s = s3;
        break;
      case 5:
        s = s4;
        break;
      case 6:
        s = s5;
        break;
      case 7:
        s = s6;
        break;
      default:
        return 1;
    }
    
    *nrow = s[0];
    *ncol = s[1];
    *colind = s + 2;
    *row = s + 2 + (*ncol + 1);
    return 0;
}

solver_int32_default FORCESNLPsolver_model_1_work(solver_int32_default *sz_iw, solver_int32_default *sz_w) 
{
    if (sz_iw) *sz_iw = 0;
    if (sz_w) *sz_w = 26;
    return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
